# Generated by Django 4.0.3 on 2022-03-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('Roll_No', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English', models.IntegerField()),
                ('Tamil', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('Roll_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_details.student')),
            ],
        ),
    ]
