# Generated by Django 4.0.3 on 2022-03-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='maths',
            new_name='c',
        ),
    ]
