# Generated by Django 4.0.3 on 2022-03-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0002_rename_maths_marks_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='c',
            new_name='maths',
        ),
    ]
